### PR TITLE
ddl: fix using name to check whether a column/index is modifying on `onModifyColumn` func

### LINKED ISSUE #76: Alter table with `RenameIndex` and `ModifyColumn` are not changed related columns
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table a (a int, b double, index i(a, b));
alter table a rename index i to i1, change column b c int;
show create table a;
```

### 2. What did you expect to see? (Required)

```
mysql> show create table a;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| a     | CREATE TABLE `a` (
  `a` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  KEY `i1` (`a`,`c`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> show create table a;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| a     | CREATE TABLE `a` (
  `a` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  KEY `i1` (`a`,`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

found by schrddl test https://github.com/tangenta/tidb/issues/63

### LINKED ISSUE #78: `getChangingIndexOriginName` func doesn't process index which named like `%_%` correctly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int, b double, index i_(a, b));
alter table t modify column b int;
show create table t;
```

### 2. What did you expect to see? (Required)

```
mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                          |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
   KEY `i_` (`a`,`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                          |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #76, close #78

Problem Summary:
1. Using index/column name to verify it's generate by modify column or not which is not accurate. Add a param in index info to verify it.
2. Rename index should also rename generated index.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/column.go [hunk 1]
```diff
@@ -936,7 +938,7 @@ func updateNewIndexesCols(changingIdxs []*model.IndexInfo,
 				idx.Columns[i].Offset = newOffset
 			} else {
 				if !hasOtherChangingCol {
-					hasOtherChangingCol = getChangingColumnOriginName(col) != col.Name.O
+					hasOtherChangingCol = getColumnInfoByName(tblInfo, col.Name.L) == nil
```
Comment (tangenta) [inline ddl/column.go]:
```suggestion
					hasOtherChangingCol = tblInfo.Columns[col.Offset].State != model.StatePublic
```
