### PR TITLE
ddl: refine `rebase auto_increment` check

### LINKED ISSUE #105: Didn't check `alter auto_increment` in ddl_work.go
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int auto_increment, key i(a));
alter table t auto_increment = 100, auto_increment = 10;
```

### 2. What did you expect to see? (Required)

see warnings like
```
mysql> show warnings;
+-------+------+--------------------------------------------------------------------------+
| Level | Code | Message                                                                  |
+-------+------+--------------------------------------------------------------------------+
| Note  | 1105 | Can't reset AUTO_INCREMENT to 10 without FORCE option, using 100 instead |
+-------+------+--------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

no warnings

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #105

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -3263,13 +3263,14 @@ func (d *ddl) RebaseAutoID(ctx sessionctx.Context, ident ast.Ident, newBase int6
 			return err
 		}
 		if newBase != newBaseTemp {
-			ctx.GetSessionVars().StmtCtx.AppendWarning(
+			ctx.GetSessionVars().StmtCtx.AppendNote(
 				fmt.Errorf("Can't reset AUTO_INCREMENT to %d without FORCE option, using %d instead",
 					newBase, newBaseTemp,
 				))
```
Comment (tangenta) [inline ddl/ddl_api.go]:
```suggestion
			ctx.GetSessionVars().StmtCtx.AppendNote(
				fmt.Errorf("Can't reset AUTO_INCREMENT to %d without FORCE option", newBase))
```

**Review by tangenta — APPROVED** [review]
