### PR TITLE
ddl: rollback multi-schema-change job when transfer to non-revertible failed

### LINKED ISSUE #90: `modify column` subjob didn't success, but ddl return success
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int);
alter table t modify column a int null default 1 after a, add column c int;
show create table t;
```

### 2. What did you expect to see? (Required)

ddl failed or ```show create table``` get a correct result.

### 3. What did you see instead (Required)

ddl success but column doesn't change.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #90

Problem Summary:

When multi-schema-change job change status from revertable to non-revertable we also should check the error message and rollback it when job failed.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/multi_schema_change.go [hunk 1]
```diff
@@ -93,19 +93,33 @@ func onMultiSchemaChange(w *worker, d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
-		for _, sub := range job.MultiSchemaInfo.SubJobs {
+		for i, sub := range job.MultiSchemaInfo.SubJobs {
 			if isFinished(sub) {
 				continue
 			}
 			proxyJob := cloneFromSubJob(job, sub)
 			ver, err = w.runDDLJob(d, t, proxyJob)
 			mergeBackToSubJob(proxyJob, sub)
+			if err != nil {
+				job.MultiSchemaInfo.Revertible = true
```
Comment (tangenta) [inline ddl/multi_schema_change.go]: We can set this to `false` after all the sub-job run successfully.

Comment (Defined2014) [reply ddl/multi_schema_change.go]: IMO, we can't do this. Because we use `if job.MultiSchemaInfo.Revertible` in many sub-jobs to verify we should return or not.

Comment (tangenta) [reply ddl/multi_schema_change.go]: The meaning of `MultiSchemaInfo.Revertible` is different between the parent job and the sub-job.

- For parent job: all the sub-jobs are non-revertible
- For sub-job: the current job is about to be non-revertible

Here we refer to the parent job.

**Review by tangenta — APPROVED** [review]
