### PR TITLE
ddl, parser: reimplement check for multi-schema-change

### LINKED ISSUE #24: Need to check dependencies with `add column ... after ...`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
create table t(a int, b int);
alter table t add column c after b, drop column b;
```

### 2. What did you expect to see? (Required)
Get error before runDDLJob

### 3. What did you see instead (Required)
Didn't get error.

### LINKED ISSUE #25: Support check `ModifyColumn` `AlterColumn` and `ChangeColumn`

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #24, #25

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -4469,6 +4469,12 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, sctx sessionctx.Contex
 		CtxVars: []interface{}{needChangeColData},
 		Args:    []interface{}{&newCol, originalColName, spec.Position, modifyColumnTp, newAutoRandBits},
 	}
+	if info := sctx.GetSessionVars().StmtCtx.MultiSchemaInfo; info != nil {
+		info.AddColumns = append(info.AddColumns, newCol.ColumnInfo)
+		if newCol.Name.L != originalColName.L {
+			info.DropColumns = append(info.DropColumns, col.ColumnInfo)
+		}
+	}
```
Comment (tangenta) [inline ddl/ddl_api.go]: `info.AddColumns` is appended even if it is rename job?

Comment (Defined2014) [reply ddl/ddl_api.go]: I think there is a better way to avoid this, rewrite the check functions now.

**Review by tangenta — APPROVED** [review]
