### PR TITLE
ddl: fix multi-schema change success when sub-job failed

### LINKED ISSUE #74: Unexpect success for `modify column` with multi-schema-change
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(a bigint null default '1761233443433596323', index t(a));
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t set a = '-7184819032643664798';
Query OK, 1 row affected (0.00 sec)

mysql> alter table t change column a b datetime null default '8972-12-24 10:56:03';
ERROR 1292 (22007): Incorrect time value: '-7184819032643664798'

mysql> alter table t change column a b datetime null default '8972-12-24 10:56:03', rename index t to t1;
Query OK, 0 rows affected (0.76 sec)
```

### 2. What did you expect to see? (Required)

Both failed

### 3. What did you see instead (Required)

Multi-Schema-Change not fail.

### 4. What is your TiDB version? (Required)

found by schrddl test #63

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #74

Problem Summary: `ReorgMeta` don't set in multi-schema change job which will cause SQL Mode equals to nil and ignore errors when data truncated in column modify.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/multi_schema_change_test.go [hunk 1]
```diff
@@ -812,6 +812,12 @@ func TestMultiSchemaChangeModifyColumns(t *testing.T) {
 	tk.MustQuery("select * from t use index(i1, i2);").Check(testkit.Rows("1 3 2", "11 33 22"))
 	tk.MustExec("admin check table t;")
 	checkDelRangeCnt(tk, jobIDExt.jobID, 1) // only i2 has tmp index.
+
+	// issue link: https://github.com/tangenta/tidb/issues/74
```
Comment (tangenta) [inline ddl/multi_schema_change_test.go]:
```suggestion
```
